CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(155),
    email VARCHAR(155) UNIQUE,
    role INTEGER DEFAULT 0,
    status INTEGER DEFAULT 0,
    user_account_type INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);